---
- hosts: localhost
  user: milesfrance
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    #  - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - geerlingguy.homebrew

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
    - include: tasks/filedir.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
