---

- name: Install Mac App Store apps.
  shell: mas list | grep {{ item }} || mas install {{ item }}
  with_items:
    - 497799835 # xcode
    - 405399194 # kindle
    - 405399194 # yubikey
    - 926036361 # lastpass
    - 409201541 # pages - complains about user id :/
    - 409183694 # keynote
    - 409203825 #numbers
    - 1147396723 #whats app
    - 1116599239 #nordVPN
  register: result
  changed_when: result.stdout.find('Installed') != -1
