---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: open files/terminal/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
    - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# Sudoers configuration (enables more convenient Vagrant usage).
- name: Copy sudoers configuration into place.
  copy:
    src: files/etc/sudoers
    dest: /etc/sudoers
    mode: 0440
    validate: 'visudo -cf %s'
  sudo: yes
  when: configure_sudoers

- name: Clone Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"

- name: Link Sublime Text folder to Dropbox folder.
  file:
    src: "~/Dropbox/programs/Sublime\ Text\ 3"
    dest: "~/Library/Application\ Support/Sublime\ Text\ 3"
    force: true
    state: link
  sudo: no
  with_items: sublime_text

- name: Create web folder.
  file:
    path: "~/Documents/web"
    state: "directory"

- name: Symlinks for web directory.
  file:
    src: "~/Documents/web"
    dest: "/web"
    force: true
    state: link
  sudo: yes
  with_items: web_root
